name: Update Credly Badges

on:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update Credly Badges
        uses: jd-35656/readme-credly-badges@v1
        with:
          credly_username: 'chandrakanth-mullella'
          badge_size: '85x85'
          badge_sort_by: 'issued'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          github_branch: 'main'
          readme_file: 'README.md'
          commit_message: 'Updated README with Credly badges'
